import { defineStore } from 'pinia';

export default defineStore('styles', {
   state: () => ({
      defaultColorTheme: {
         tabBackgroundColor: '#FFFFFF',
         tabFontColor: '#000000',
         tabSliderColor: '#000000',
         titleBarColor: '#E8EAEC',
         titleBarFontColor: '#000000',
         navBackgroundColor: '#FFFFFF',
         navFontColor: '#000000',
         cardBgColor: '#ffffff',
         primary: '#2B3142',
         secondary: '#B61E4E',
         accentColor: '#215E87',
         accentFontColor: '#FFFFFF',
         pageBackgroundColor: '#E8EAEC',
         pageFontColor: '#000000',
         drawerBgColor: '#E8EAEC',
         drawerColor: '#000000',
         drawerCardBgColor: '#FFF',
         applicationMenuBackgroundColor: '#FFF',
         applicationMenuItemBackgroundColor: '#FFF',
      },
      administrationColorTheme: {
         tabBackgroundColor: '#1e1e1e',
         tabFontColor: '#ffffff',
         tabSliderColor: '#2B3142',
         titleBarColor: '#1e1e1e',
         titleBarFontColor: '#ffffff',
         navBackgroundColor: '#1e1e1e',
         navFontColor: '#ffffff',
         cardBgColor: '#1e1e1e',
         primary: '#1e1e1e',
         secondary: '#272727',
         accentColor: '#B61E4E',
         accentFontColor: '#ffffff',
         pageBackgroundColor: '#272727',
         pageFontColor: '#ffffff',
         drawerBgColor: '#272727',
         drawerCardBgColor: '#1e1e1e',
         drawerColor: '#ffffff',
         black: '#000000',
         applicationMenuBackgroundColor: '#272727',
         applicationMenuItemBackgroundColor: '#1E1E1E',
      },
      colorTheme: {
         tabBackgroundColor: '#FFFFFF',
         tabFontColor: '#000000',
         tabSliderColor: '#000000',
         titleBarColor: '#E8EAEC',
         titleBarFontColor: '#000000',
         navBackgroundColor: '#FFFFFF',
         navFontColor: '#000000',
         cardBgColor: '#ffffff',
         primary: '#2B3142',
         secondary: '#B61E4E',
         grey: '#272727',
         accentColor: '#215E87',
         accentFontColor: '#FFFFFF',
         pageBackgroundColor: '#E8EAEC',
         pageFontColor: '#000000',
         drawerBgColor: '#E8EAEC',
         drawerColor: '#000000',
         applicationMenuBackgroundColor: '#FFF',
         applicationMenuItemBackgroundColor: '#FFF',
      },
   }),
   getters: {},
   actions: {
      async toggleColorTheme(view) {
         Object.assign(this.colorTheme, { ...this[`${view}ColorTheme`] });
      },
   },
});
